### ISSUE TITLE
It there anyway to send canvas dataURL from client to Node server with out client form?

### ISSUE THREAD

**Issue by suijunqiang** [deepikagunda/imageUpload#1]
Hello, Deepikagunda,

First of all, thank you for sharing the great project.

Your imageUpload is running well on my server/client.
 But I have met another issue like that I am trying to send a lot canvas dataURLs to server side with out HTML form, and the canvas dataURL datas is generated by a webcam video.

In fact, client canvas dataURLs have been uploaded to your server side with wrong format( all image with same size of 6365 byte).

So my question is that is there any way to do that?(to send a lot canvas to your server?).
Would you please me to figure it out?

here is my whatsapp/Wechat/QQ 
18018692866/18018692866/66399755

Thanks & Best Regards
Sui

**Comment by suijunqiang** [comment]
Or any way to upload base64 automatically by ajax?

**Comment by deepikagunda** [comment]
Hi sui,
I would assume it should work.

I think there is one issue.the express might not allow files beyond a
certain size to be uploaded.pls check the limits

https://stackoverflow.com/questions/31967138/node-js-express-bodyparser-post-limit

Upload one file of larger size n see.later try for multiple files.

I think  express is set to limit it..and that's why you see all files of
same size.
Good luck,
Deepika

**Comment by suijunqiang** [comment]
dear, Deepikagunda
Thanks for your feedback.
I have fixed the send/receive issue by using socket.io, in my case it is a good choose.
express body-parser has to use client form and it's not easy to send a lot images automatically with out any interfere by users.

Any way thanks for helping.
Sui
